config/routes.rb
Rails.application.routes.draw do
  resources :burgers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/burger.rb
class Burger < ApplicationRecord
    def nutriments
        #recuperer données api --> faire tableau
        #codeBurger = "3029330003533"

        codeBurger = self.code
        product = Openfoodfacts::Product.get(codeBurger, locale: 'fr')
        if product
            return product.nutriments.to_hash
        else
            return [""]
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/burgers_controller.rb
class BurgersController < ApplicationController
  before_action :set_burger, only: [:show, :edit, :update, :destroy]

  # GET /burgers
  # GET /burgers.json
  def index
    @burgers = Burger.all
  end

  # GET /burgers/1
  # GET /burgers/1.json
  def show
    # for nutriment in @burger.nutriments
    # end
    # p @burger.nutriments
  end
  

  # GET /burgers/new
  def new
    @burger = Burger.new
  end

  # GET /burgers/1/edit
  def edit
  end

  # POST /burgers
  # POST /burgers.json
  def create
    @burger = Burger.new(burger_params)

    respond_to do |format|
      if @burger.save
        format.html { redirect_to @burger, notice: 'Burger was successfully created.' }
        format.json { render :show, status: :created, location: @burger }
      else
        format.html { render :new }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /burgers/1
  # PATCH/PUT /burgers/1.json
  def update
    respond_to do |format|
      if @burger.update(burger_params)
        format.html { redirect_to @burger, notice: 'Burger was successfully updated.' }
        format.json { render :show, status: :ok, location: @burger }
      else
        format.html { render :edit }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /burgers/1
  # DELETE /burgers/1.json
  def destroy
    @burger.destroy
    respond_to do |format|
      format.html { redirect_to burgers_url, notice: 'Burger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_burger
      @burger = Burger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def burger_params
      params.require(:burger).permit(:Name, :Price, :Image, :Nutriscore, :code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/burgers_helper.rb
module BurgersHelper
end

app/views/burgers/_form.html.erb
<%= form_with(model: burger, local: true) do |form| %>
  <% if burger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(burger.errors.count, "error") %> prohibited this burger from being saved:</h2>

      <ul>
      <% burger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name, id: :burger_Name %>
  </div>

  <div class="field">
    <%= form.label :Price %>
    <%= form.text_field :Price, id: :burger_Price %>
  </div>

  <div class="field">
    <%= form.label :Image %>
    <%= form.text_field :Image, id: :burger_Image %>
  </div>

  <div class="field">
    <%= form.label :Nutriscore %>
    <%= form.text_field :Nutriscore, id: :burger_Nutriscore %>
  </div>

  <div class="field">
    <%= form.label :Code %>
    <%= form.text_field :code, id: :burger_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/burgers/edit.html.erb
<h1>Editing Burger</h1>

<%= render 'form', burger: @burger %>

<button>
<%= link_to 'Show', @burger %> 
</button>

<button>
<%= link_to 'Back', burgers_path %>
</button>

app/views/burgers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Burgers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Image</th>
      <th>Nutriscore</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @burgers.each do |burger| %>
      <tr>
        <td><%= burger.Name %></td>
        <td><%= burger.Price %></td>
        <td><%= burger.Image %></td>
        <td><%= burger.Nutriscore %></td>
        <td><%= burger.code %></td>
      
        <td><button>
          <%= link_to 'Show', burger %>
        </button></td>
      
        <td><button>
          <%= link_to 'Edit', edit_burger_path(burger) %>
        </button></td>

        <td><button>
          <%= link_to 'Destroy', burger, method: :delete, data: { confirm: 'Are you sure?' } %>
        </button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button>
<%= link_to 'New Burger', new_burger_path %>
</button>

app/views/burgers/new.html.erb
<h1>New Burger</h1>

<%= render 'form', burger: @burger %>

<button>
<%= link_to 'Back', burgers_path %>
</button>

app/views/burgers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @burger.Name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @burger.Price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @burger.Image %>
</p>

<p>
  <strong>Nutriscore:</strong>
  <%= @burger.Nutriscore %>
</p>

<p>
  <strong>Code:</strong>
  <%= @burger.code %>
</p>

<p>
  <strong>Nutriments:</strong>
</p>
<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Quantité</th>
    </tr>
  </thead>

  <tbody>
    <% @burger.nutriments.each do |burger| %>
    <tr>
      <td><%= burger[0] %></td>
      <td><%= burger[1] %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<button>
<%= link_to 'Edit', edit_burger_path(@burger) %> |
</button>
<button>
<%= link_to 'Back', burgers_path %>
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appli Multimedia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>